/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/worker-configuration.d.ts` (hash: b6da27f6a78b5e5772139cc397cd1ede)
interface __BaseEnv_Env {
	LOADER: WorkerLoader;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
