packages:
  - "packages/*"
allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - '@astrojs/cloudflare@14.0.0'
  - '@astrojs/markdown-satteri@0.3.1'
  - '@astrojs/svelte@9.0.0'
  - astro@7.0.0
