// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Frontmatter = 1,
  RawElement = 2,
  Comment = 3,
  Expression = 4,
  Document = 5,
  Element = 6,
  OpenTag = 9,
  TagName = 10,
  Attribute = 11,
  AttributeName = 12,
  AttributeValue = 14,
  AttributeString = 15,
  UnquotedValue = 16,
  CloseTag = 18,
  SelfClosingTag = 20,
  Text = 21
