// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {frontmatterToken, contentTokens, expressionToken} from "./tokens.js"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$tOkO_OOOrQ`O'#CeO!YO^O'#CbOOOU'#Cb'#CbOOOU'#Cr'#CrO!aO^O'#CwQOOOOOOVO^OOOOQS'#Cf'#CfO!kQdO,59PO!yOWO,58|OOOU-E6p-E6pOOQS'#Ch'#ChO#OQdO'#CgOOQS'#Cg'#CgOOQS'#Cs'#CsO#aQdO1G.kOOOU1G.k1G.kOOOU1G.v1G.vOrQ`O'#CnOOOU1G.h1G.hO#oQtO,59ROOQS-E6q-E6qOOOU7+$V7+$VOOOU7+$b7+$bO#zQ`O,59YOOQS'#Cj'#CjOOQS1G.m1G.mOOOU1G.t1G.t",
  stateData: "$P~OjOS~OQSORSOSSOWPOeSOhkP~OPVO~PVOlWO~OQSORSOSSOWPOeSO~OakP~PwOhkXakX~PwOS^OVaOcbOl[O~OacO~O]eOSZXVZXcZXlZX~OS^OVgOchOl[O~OSjO_jO`jO~OVlO~O",
  goto: "!zlPPPPPPmPPsy!P!TP!XPPP![P!_P!e!mPPP!sXSOQTVXQOQTVQXPRicT_X`T]X`RkeRdYXROQTVUTOQVRZTQ`XRf`SUOVRYQ",
  nodeNames: "⚠ Frontmatter RawElement Comment Expression Document Element > < OpenTag TagName Attribute AttributeName = AttributeValue AttributeString UnquotedValue </ CloseTag /> SelfClosingTag Text",
  maxTerm: 28,
  nodeProps: [
    ["openedBy", 7,"< </",19,"<"],
    ["closedBy", 8,"> />",17,">"]
  ],
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: ".z~RqOX#YXY%aYZ%aZ]#Y]^%a^p#Ypq%aqr#Yrs&^st#Ytu(Zuw#Ywx*_x!P#Y!P!Q+o!Q![#Y![!](Z!]!^#Y!^!_-o!_!`-|!`!a.d!a!b#Y!b!c(Z!c!}(Z!}#R#Y#R#S(Z#S#T$o#T#o(Z#p#q#Y#q#r$o#r;'S#Y;'S;=`%Z<%lO#YT#adeP`SOX#YXZ$oZ]#Y]^$o^p#Ypq$oqr#Yrs$osw#Ywx$ox!^#Y!_!a$o!a#S#Y#S#T$o#T#o#Y#p#q#Y#q#r$o#r;'S#Y;'S;=`%Z<%lO#YP$tTePO!^$o!_#o$o#p;'S$o;'S;=`%T<%lO$oP%WP;=`<%l$oT%^P;=`<%l#YV%h[ePjUOX$oXY%aYZ%aZ]$o]^%a^p$opq%aq!^$o!_#o$o#p;'S$o;'S;=`%T<%lO$oT&cXePOr&^rs'Os!^&^!^!_'f!_#o&^#o#p'f#p;'S&^;'S;=`(T<%lO&^T'VT_SePO!^$o!_#o$o#p;'S$o;'S;=`%T<%lO$oS'iTOr'frs'xs;'S'f;'S;=`'}<%lO'fS'}O_SS(QP;=`<%l'fT(WP;=`<%l&^V(dmeP`SlQOX#YXZ$oZ]#Y]^$o^p#Ypq$oqr#Yrs$osw#Ywx$ox}#Y}!O(Z!O!P(Z!P!Q#Y!Q![(Z![!](Z!]!^#Y!_!a$o!a!c#Y!c!}(Z!}#R#Y#R#S(Z#S#T$o#T#o(Z#p#q#Y#q#r$o#r;'S#Y;'S;=`%Z<%lO#YT*dXePOw*_wx'Ox!^*_!^!_+P!_#o*_#o#p+P#p;'S*_;'S;=`+i<%lO*_S+STOw+Pwx'xx;'S+P;'S;=`+c<%lO+PS+fP;=`<%l+PT+lP;=`<%l*_V+veeP`SOX#YXZ$oZ]#Y]^$o^p#Ypq$oqr#Yrs$osw#Ywx$ox!^#Y!_!`$o!`!a-X!a#S#Y#S#T$o#T#o#Y#p#q#Y#q#r$o#r;'S#Y;'S;=`%Z<%lO#YR-`TcQePO!^$o!_#o$o#p;'S$o;'S;=`%T<%lO$o~-tPW~!P!Q-w~-|Oa~R.TT]QePO!^$o!_#o$o#p;'S$o;'S;=`%T<%lO$oR.kTVQePO!^$o!_#o$o#p;'S$o;'S;=`%T<%lO$o",
  tokenizers: [frontmatterToken, contentTokens, expressionToken, 0, 1, 2],
  topRules: {"Document":[0,5]},
  tokenPrec: 0
})
