// This file was generated by lezer-generator. You probably shouldn't edit it.
import { LRParser } from "@lezer/lr";
import {
	commentToken,
	expressionToken,
	frontmatterToken,
	rawTextToken,
} from "./tokens.js";

const spec_identifier = { __proto__: null, script: 66, style: 68 };
export const parser = LRParser.deserialize({
	version: 14,
	states:
		"&`OhOgOOOoQpO'#CeOzOhO'#CqO!SOfO'#CbOOOU'#Cb'#CbOOOU'#Cv'#CvO!eOfO'#C{QOOOOOOVOfOOOOQS'#Cf'#CfO!yQtO,59POOQS'#Cs'#CsO#XQtO,59^OrQpO'#CtOOOU,59],59]O}O`O,59]O#dO`O,58|OOOU-E6t-E6tOOQS'#Ch'#ChO#iQtO'#CgOOQS'#Cg'#CgOOQS'#Cw'#CwO#zQtO1G.kOOOU1G.k1G.kOOOU1G.v1G.vO$YQtO1G.xOOOW1G.x1G.xO$eQpO,59`OOOU1G.w1G.wO$jQpO'#CnOOOU1G.h1G.hO$oQ!fO,59ROOQS-E6u-E6uOOOU7+$V7+$VOOOU7+$b7+$bOOOW7+$d7+$dOOOU1G.z1G.zO$zQpO,59YOOQS'#Cj'#CjOOQS1G.m1G.mOOOU1G.t1G.t",
	stateData:
		"%P~OnOS~OQTORTOWPOiTOloP~OPWO~PVOpXOqZOrZO~OS_Oa]O~OQTORTOWPOiTOaoP~OQTORTOWPOiTOloXaoX~ORdOVgOchOpbO~ORdOVjOpbO~OamO~O]oORZXVZXcZXpZX~ORdOVqOcrOpbO~ORdOVsOpbO~OVtO~OpXO~ORvO_vO`vO~OVxO~O",
	goto: "#jpPPPPPPqPPw}!T!ZP!aPPP!dP!g!g!m!s!yP#P#XPPP#cXTORUWXRORUWQYPRumXeY[fiXcY[fiRwoRn`XSORUWXQORUWQ[PRk]Q^QRl_UUORWRaUQfYQi[TpfiSVOWR`R",
	nodeNames:
		"⚠ Frontmatter Comment Expression RawText Document Element > < OpenTag TagName Attribute AttributeName = AttributeValue AttributeString UnquotedValue </ CloseTag /> SelfClosingTag RawElement RawOpenTag RawTagName RawCloseTag Text",
	maxTerm: 34,
	nodeProps: [
		["openedBy", 7, "< </", 19, "<"],
		["closedBy", 8, "> />", 17, ">"],
	],
	skippedNodes: [0],
	repeatNodeCount: 2,
	tokenData:
		".z~RqOX#YXY%aYZ%aZ]#Y]^%a^p#Ypq%aqr#Yrs&^st#Ytu(Zuw#Ywx*_x!P#Y!P!Q+o!Q![#Y![!](Z!]!^#Y!^!_-o!_!`-|!`!a.d!a!b#Y!b!c(Z!c!}(Z!}#R#Y#R#S(Z#S#T$o#T#o(Z#p#q#Y#q#r$o#r;'S#Y;'S;=`%Z<%lO#YT#adiP`SOX#YXZ$oZ]#Y]^$o^p#Ypq$oqr#Yrs$osw#Ywx$ox!^#Y!_!a$o!a#S#Y#S#T$o#T#o#Y#p#q#Y#q#r$o#r;'S#Y;'S;=`%Z<%lO#YP$tTiPO!^$o!_#o$o#p;'S$o;'S;=`%T<%lO$oP%WP;=`<%l$oT%^P;=`<%l#YV%h[iPnUOX$oXY%aYZ%aZ]$o]^%a^p$opq%aq!^$o!_#o$o#p;'S$o;'S;=`%T<%lO$oT&cXiPOr&^rs'Os!^&^!^!_'f!_#o&^#o#p'f#p;'S&^;'S;=`(T<%lO&^T'VT_SiPO!^$o!_#o$o#p;'S$o;'S;=`%T<%lO$oS'iTOr'frs'xs;'S'f;'S;=`'}<%lO'fS'}O_SS(QP;=`<%l'fT(WP;=`<%l&^V(dmiP`SpQOX#YXZ$oZ]#Y]^$o^p#Ypq$oqr#Yrs$osw#Ywx$ox}#Y}!O(Z!O!P(Z!P!Q#Y!Q![(Z![!](Z!]!^#Y!_!a$o!a!c#Y!c!}(Z!}#R#Y#R#S(Z#S#T$o#T#o(Z#p#q#Y#q#r$o#r;'S#Y;'S;=`%Z<%lO#YT*dXiPOw*_wx'Ox!^*_!^!_+P!_#o*_#o#p+P#p;'S*_;'S;=`+i<%lO*_S+STOw+Pwx'xx;'S+P;'S;=`+c<%lO+PS+fP;=`<%l+PT+lP;=`<%l*_V+veiP`SOX#YXZ$oZ]#Y]^$o^p#Ypq$oqr#Yrs$osw#Ywx$ox!^#Y!_!`$o!`!a-X!a#S#Y#S#T$o#T#o#Y#p#q#Y#q#r$o#r;'S#Y;'S;=`%Z<%lO#YR-`TcQiPO!^$o!_#o$o#p;'S$o;'S;=`%T<%lO$o~-tPW~!P!Q-w~-|Oa~R.TT]QiPO!^$o!_#o$o#p;'S$o;'S;=`%T<%lO$oR.kTVQiPO!^$o!_#o$o#p;'S$o;'S;=`%T<%lO$o",
	tokenizers: [
		frontmatterToken,
		commentToken,
		expressionToken,
		rawTextToken,
		0,
		1,
		2,
	],
	topRules: { Document: [0, 5] },
	specialized: [{ term: 32, get: (value) => spec_identifier[value] || -1 }],
	tokenPrec: 0,
});
